name: Docker Image CI

on:
  push:
    branches: [ "Dragon" ]
  pull_request:
    branches: [ "ğ€ğ‘ğ‹ğğƒğ‘ğ€ğ†ğğ" ]

jobs:

  build:

    runs-on: ğ€ğ‘ğ‹ğğƒğ‘ğ€ğ†ğğ-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
